# Generated by Django 5.1.6 on 2025-02-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_subjects_usersubjects_subjects_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubjects',
            name='last_study',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
