# Generated by Django 5.1.6 on 2025-02-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_usersubjects_last_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubjects',
            name='correct_questions',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usersubjects',
            name='wrong_questions',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
