# Generated by Django 5.1.6 on 2025-02-28 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_usersubjects_correct_questions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubjects',
            old_name='correct_questions',
            new_name='correct_answers',
        ),
        migrations.RenameField(
            model_name='usersubjects',
            old_name='wrong_questions',
            new_name='wrong_answers',
        ),
    ]
