# Generated by Django 5.1.6 on 2025-02-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_usersubjects_last_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubjects',
            name='correct_answers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubjects',
            name='time_studied',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubjects',
            name='wrong_answers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
