# Generated by Django 5.1.6 on 2025-02-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_usersubjects_correct_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubjects',
            name='last_study',
            field=models.DateField(blank=True, null=True),
        ),
    ]
